package boletin_2_condicionales_y_bucles05_1;

import java.util.Random;

import util.*;

public class Main {
    public static void main() {
        System.out.println(
                "\n5. Realizar un juego para adivinar un número. Para ello pedir un número N, y luego ir pidiendo números indicando “mayor” o “menor” según sea mayor o menor con respecto a N. El proceso termina cuando el usuario acierta.\n");

        Random N; // constructor - object
        int number_generated; // integer generated by the constructor
        int number_user; // number typed by the user

        N = new Random();
        number_generated = N.nextInt(101);

        System.out.println("Please, try to guess the number:\n");
        number_user = Entrada.entero();

        while (number_user != number_generated) {

            if (number_user > number_generated) {
                System.out.println(ConsoleColors.warning("\nThe number you typed is higher, try lower! (-) \n"));
            } else {
                System.out.println(ConsoleColors.warning("\nThe number you typed is lower, try higher! (+) \n"));
            }

            number_user = Entrada.entero();
        }

        System.out.println(ConsoleColors.success("\nCongratulations, you guessed!\n"));

    }
}