package variables_y_condicionales2;

import util.Entrada;

public class Main {
    public static void main(String[] args) {
        System.out.println("Boletin 1 - Variables y condicionales \n");

        // Declaración de variables

        // Radio de la circunferencia
        int radio;

        System.out.println("Type the value for the radius of the circle: \n");
        radio = Entrada.entero();
    }

}